### PR TITLE
Graphql kotlin

### PR DESCRIPTION
**Pull request by Francynox**
@ESchouten I added argument renaming to graphql-kotlin although the way I did it is a little unusual

I worked with the Hook methods `didGenerateQueryField` and `didGenerateMutationField` to modify the schema and rename the arguments

Doing this broke the DataFetcher (the original implementation compares the name of the query argument with the name of the function parameter, if there is a match calls the `convertArgumentValue` for the conversion)... This method `convertArgumentValue ` is internal and not public, so I had to retrieve it with reflections

I honestly don't understand the purpose of the two methods `didGenerateQueryField` and `didGenerateMutationField`, because every change in the schema results in a break in the datafetcher

### CODE REVIEW

**Comment by ESchouten** [comment]
Interesting and good work
Named, non-generic, arguments are very much needed for a proper API
I've taken a look at [Kaguya](https://github.com/cufyorg/kaguya), also based on graphql-java, and next to being a lot simpler, it seems like custom named arguments are supported as well (see the example in the README).
Downside is ofcourse how new the library is. 
What do you think?

**Comment by Francynox** [comment]
For a future implementation of [Kaguya](https://github.com/cufyorg/kaguya) are you thinking of implementing some sort of automatic creation of graphql objects, queries and mutations or creating everything manually?

I think manual creation will add more complexity to the graphql server, but more control over customization.

**Comment by ESchouten** [comment]
Definitely automatic creation. I see Kaguya as a replacement for how we use KGraphql now.
What do you think? Kaguya vs Graphql-Kotlin?

**Comment by Francynox** [comment]
@ESchouten 
Kaguya, at the curernt state, is missing features as subscriptions and federations, which could perhaps be useful for future implementations.

But In my opinion i'll definetelly go with Kaguya as I see it as more "clean" than Graphql-Kotlin; I think complex libraries can create problems and complicate the code unnecessarily

**Comment by ESchouten** [comment]
Relevant discussion for #12

**Comment by LSafer** [comment]
Hi, I am very happy to see you interested in `Kaguya`  😊

> @ESchouten Kaguya, at the curernt state, is missing features as subscriptions and federations, which could perhaps be useful for future implementations.

About the missing features,

First of all, as you might noticed, I made the builders in `Kaguya` inherit the ones in `graphql-java`  so 
anything not officially supported (but supported in `graphql-java`) can still be used elegantly. 😉

Second, I am very open for pull-requests and I log in to GitHub regularly  🤗

Also, I am thinking about building `Kaguya` independently with its own 
parsers and runtime 😙 (I am calling it `Kaguya-Supremacy`)

But, for now you might use the first and second solutions since I have a lot of work to do 
since I work a full-time job ☹

**Comment by LSafer** [comment]
The thing about `graphql-java` is it is very tricky to work around.
You cannot add your own data types but you can still implement `GraphQLType`
While this might suggest you can tweak the parser but it just breaks everything when you try.

For now, `Kaguya` is very great on delegating to `graphql-java` and it will always be just 
a wrapper. (since I am not ready to implement the parser yet)

Then, the new `Kaguya-Supremacy` will be built to be more customizable and tweakable
while remaining simple.

**Pull request merged**
